<?php

return [
    'subjects' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên môn học</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'capabilities' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên năng lực</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'qualities' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên phẩm chất</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'support' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center w-25',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tiêu đề</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'transaction' => [
        'code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã giao dịch</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'user_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-user"></i><span>Khách hàng</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'amount' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-currency-dollar"></i><span>Số tiền</span></div>',
            'width' => '150px',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'package_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-package"></i><span>Gói dịch vụ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'service' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-layout-grid"></i><span>Cổng dịch vụ</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-small"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'width' => '150px',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'eq' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'child_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Trẻ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'parent_code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã cha/Mẹ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'self_regulation' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Kiểm soát cảm xúc</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'social_awareness' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Nhận thức cảm xúc</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'relationship_management' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Đồng cảm</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'decision_making' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Động lực</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'optimism' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Kỹ năng xã hội</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'score' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Điểm</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'description' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Mô tả</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
            'visible' => false,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'aq' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'child_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Trẻ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'parent_code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã cha/Mẹ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'score' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Điểm</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'positivity' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tính tích cực</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'self_reflection' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Khả năng tự phản hồi</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'flexibility' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tính linh hoạt</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'perseverance' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tính kiên trì</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'endurance' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Khả năng chịu đựng</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'description' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Mô tả</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
            'visible' => false,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'iq' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'child_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Trẻ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'parent_code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã cha/Mẹ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'tag' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-tags"></i><span>Thẻ tag</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'score' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Điểm</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'badge_image' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-photo"></i><span>hình ảnh</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'description' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Mô tả</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
            'visible' => false,
        ],
        'updated_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'expected' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-hash"></i><span>Xem thông tin</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'age' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Tuổi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'height_expected' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-ruler-2"></i><span>Chiều cao dự kiến (cm)</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'weight_expected' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-scale"></i><span>Cân nặng dự kiến (kg)</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'journal' => [
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tiêu đề</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'child_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Trẻ em</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'classes' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'level_group' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Phân loại</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'product_catalog' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'rating_pqs' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'child_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Trẻ</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'parent_code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã cha/Mẹ</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'assessment_date' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-currency-dollar"></i><span>Ngày đánh giá</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'height' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-ruler-2"></i><span>Chiều cao (cm)</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'weight' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-scale"></i><span>Cân nặng (kg)</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'strength' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Điểm sức mạnh</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'endurance' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Điểm sức bền</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'bmi' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Chỉ số BMI</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'bmi_result' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Kết quả BMI</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'height_result' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-ruler-2"></i><span>Kết quả chiều cao</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'height_change' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-ruler-2"></i><span>Thay đổi chiều cao</span></div>',
            'orderable' => true,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'pregnancy' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'child_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Trẻ em</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'iq_questions' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã câu hỏi IQ</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'question' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-help"></i><span>Câu hỏi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'age' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Độ tuổi phù hợp</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'eq_questions' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã câu hỏi EQ</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'question' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-help"></i><span>Câu hỏi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'question_group_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-help"></i><span>Nhóm câu hỏi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'age_group' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Nhóm tuổi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'aq_questions' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã câu hỏi AQ</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'question' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-help"></i><span>Câu hỏi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'question_group_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-help"></i><span>Nhóm câu hỏi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'age_group' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Nhóm tuổi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'question_groups' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên nhóm câu hỏi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'type' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-tags"></i><span>Loại câu hỏi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'bmi' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
            'visible' => false,
        ],
        'gender' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-gender-male"></i><span>Giới tính</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'age' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Tuổi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'z_score_minus_3' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Z-score -3</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'z_score_minus_2' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Z-score -2</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'z_score_minus_1' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Z-score -1</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'z_score_0' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Z-score 0</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'z_score_plus_1' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Z-score +1</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'z_score_plus_2' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Z-score +2</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'z_score_plus_3' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Z-score +3</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'WeightHeightWho' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'gender' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-gender-male"></i><span>Giới tính</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'age' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Tuổi</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'month' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tháng</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'height' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-ruler-2"></i><span>Chiều cao (cm)</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'weight' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-scale"></i><span>Cân nặng (kg)</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'weight_change' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-scale"></i><span>Thay đổi cân nặng (kg)</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'height_change' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-ruler-2"></i><span>Thay đổi chiều cao (cm)</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'vaccination_schedule' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên mũi tiêm</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'child_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Tên trẻ</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'vaccination_type_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-tags"></i><span>Loại tiêm chủng</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'performed_on' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Thời gian tiêm</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'vaccinationType' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên vắc xin / Loại tiêm</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'position' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Vị trí</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'package' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên gói dịch vụ</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'type' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-tags"></i><span>Loại gói</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'max_devices' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-devices"></i><span>Số thiết bị</span></div>',
            'orderable' => true,
            'width' => '140px',
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => true,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'quiz_iq' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'description' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Mô tả</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'age' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Độ tuổi</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => true,
        ],
    ],
    'quiz' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên bài kiểm tra</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'description' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Mô tả</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'type' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-tags"></i><span>Phân loại</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => true,
        ],
    ],
    'clinic_type' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên loại phòng khám</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => true,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'clinic' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên phòng khám</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'clinic_type_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-tags"></i><span>Loại phòng khám</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'opening_time' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Giờ mở cửa</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'closing_time' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Giờ đóng cửa</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => true,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'exercise' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên bài tập</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'notifications' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
            'visible' => false,
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tiêu đề</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'user_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-user"></i><span>Nhân viên nhận</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'admin_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-user"></i><span>Admin nhận</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'message' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Nội dung</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày thông báo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'notifications_approval' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
            'visible' => false,
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tiêu đề</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'user_id_attribute' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-user"></i><span>Khách hàng</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'admin_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-user"></i><span>Admin nhận</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'message' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-timeline"></i><span>Nội dung</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'package_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-package"></i><span>Gói thông báo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'approval_status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày thông báo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'module' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center w-25',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-hash"></i><span>ID</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên Module</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'role' => [
        'id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-hash"></i><span>ID</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-shield-lock"></i><span>Tên vai trò</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Slug ( role_name )</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'guard_name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-shield-lock"></i><span>Vai trò của nhóm ( Guard Name )</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'permission' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-hash"></i><span>ID</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-shield-lock"></i><span>Tên quyền</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Slug ( Permission_name )</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'module_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Thuộc Module</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'guard_name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-shield-lock"></i><span>Nhóm quyền ( Guard Name )</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'type' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-shield-lock"></i><span>Loại quyền</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'admin' => [
        'fullname' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Họ tên</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'phone' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-phone"></i><span>Số điện thoại</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'email' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mail"></i><span>Email</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'roles' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-shield-lock"></i><span>Vai trò</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'visible' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'user' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
            'visible' => false,
        ],
        'code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã khách hàng</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'affiliate_code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-share"></i><span>Mã giới thiệu</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'fullname' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Họ tên</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'email' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mail"></i><span>Email</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'phone' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-phone"></i><span>Số điện thoại</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'package_name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-package"></i><span>Tên gói</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'service_type' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-brand-google"></i><span>Hình thức</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'width' => '130px',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'children' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
            'visible' => false,
        ],
        'id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã trẻ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'fullname' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Tên trẻ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'user_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã cha/Mẹ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'user_fullname' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-user"></i><span>Cha/Mẹ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'user_code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã khách hàng</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'birthday' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-cake"></i><span>Ngày sinh</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'due_date' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-cake"></i><span>Ngày dự sinh</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'gender' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-gender-male"></i><span>Giới tính</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'is_born' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tình trạng</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'slider' => [
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'plain_key' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Key</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'items' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-hash"></i><span>Slider Item</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'visible' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'slider_item' => [
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'image' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-photo"></i><span>Hình ảnh</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'position' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Vị trí hiển thị</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'visible' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'post_category' => [
        'avatar' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-photo"></i><span>Ảnh đại diện</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-category"></i><span>Tên danh mục</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'post' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
            'visible' => false,
        ],
        'image' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-photo"></i><span>Ảnh</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tiêu đề</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'is_featured' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Nổi bật</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => false,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => false,
        ],
    ],
    'gpa' => [
        'child_code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã trẻ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'parent_code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã cha/Mẹ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'children.fullname' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-mood-smile"></i><span>Họ tên trẻ</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
            'data' => 'children.fullname',
        ],
        'class.name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên lớp</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'semester1_grade' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Điểm học kỳ I</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'semester2_grade' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Điểm học kỳ II</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'full_year_grade' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-award"></i><span>Điểm Cả năm</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
    ],
    'brand' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'country' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>country</span></div>',
            'orderable' => false,
            'width' => '150px',
            'addClass' => 'text-center align-middle',
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'orderable' => false,
            'addClass' => 'text-center align-middle',
            'visible' => true,
        ],
    ],
    'product' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'code' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-code"></i><span>Mã</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'name' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tên</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'product_catalog_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-category"></i><span>Danh mục sản phẩm</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'brand_id' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Thương hiệu</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'guide' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tiêu đề</span></div>',
            'width' => '200px',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'type' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-tags"></i><span>Loại hướng dẫn</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'develop' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tiêu đề</span></div>',
            'width' => '200px',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'steps' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-list-numbers"></i><span>Danh sách các bước</span></div>',
            'width' => '200px',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'step' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'title' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Tiêu đề</span></div>',
            'width' => '200px',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'order' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Thứ tự</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'created_at' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Ngày tạo</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => true,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
    'app_versions' => [
        'checkbox' => [
            'title' => 'choose',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'align-middle text-center',
            'footer' => '<input type="checkbox" class="form-check-input check-all" />',
        ],
        'app_type' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-tags"></i><span>Loại App</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'platform' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Nền tảng</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'notify' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Notify version</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'required' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Required version</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'checking_version' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-file-text"></i><span>Checking version</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'update_url' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-calendar"></i><span>Link cập nhật</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'status' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-info-circle"></i><span>Trạng thái</span></div>',
            'addClass' => 'text-center align-middle',
            'orderable' => false,
        ],
        'action' => [
            'title' => '<div class="header-cell-content"><i class="ti ti-settings"></i><span>Thao tác</span></div>',
            'orderable' => false,
            'exportable' => false,
            'printable' => false,
            'addClass' => 'text-center align-middle',
        ],
    ],
];
