name: Deploy Laravel by Branch & Tag

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "::error::SSH_PRIVATE_KEY is not set in GitHub Secrets!"
            exit 1
          fi
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy Laravel (Rsync + SSH)
        run: |
          BRANCH="${{ github.ref_name }}"

          TARGET_DIR="/home/app2997/domains/kids360growth.com/public_html"

          # 1. Sync files from Runner -> Server
          rsync -avz \
            --exclude='.env' \
            --exclude='storage' \
            --exclude='.git' \
            --exclude='.github' \
            -e "ssh -p 24700 -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519" \
            ./ app2997@103.72.99.174:$TARGET_DIR/

          echo "✅ Deployment Complete!"
